pool:
  name: Azure Pipelines
  demands: maven

steps:
- task: JavaToolInstaller@0
  displayName: 'Use Java 11'
  inputs:
    versionSpec: 11
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    goals: 'clean test'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: MaciejMaciejewski.azure-pipelines-cucumber.PublishCucumberReport.PublishCucumberReport@1
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: '$(Parameters.jsonDir)'
    outputPath: '$(Parameters.outputPath)'
    theme: '$(Parameters.theme)'
    reportSuiteAsScenarios: '$(Parameters.reportSuiteAsScenarios)'
    name: '$(Parameters.name)'
    title: '$(Parameters.title)'

